import 'package:phone_numbers_parser/phone_numbers_parser.dart';

/// English country names → [IsoCode], for resolving the calling code and
/// national format to use for the phone field from whatever the user picked
/// in the (separately, real-backend-driven) country field.
///
/// `phone_numbers_parser` only ships ISO alpha-2 codes, not display names, so
/// this table exists to bridge `TalkamCountry.name` (arbitrary English text
/// from `/location/countries`) to it. Covers the standard English short name
/// for every country plus common alternate names/abbreviations, so a country
/// list that differs slightly in wording (e.g. "USA" vs "United States")
/// still resolves.
final Map<String, IsoCode> _countryNameToIsoCode = {
  for (final entry in _entries) entry.$1.toLowerCase(): entry.$2,
};

/// Resolves [name] (as returned by the real country list) to an [IsoCode],
/// or null if it isn't recognized — callers must treat that as "can't do
/// country-aware formatting/validation for this one" rather than an error.
IsoCode? isoCodeForCountryName(String? name) {
  if (name == null) return null;
  final key = name.trim().toLowerCase();
  if (key.isEmpty) return null;
  return _countryNameToIsoCode[key];
}

/// The "+<code>" calling code for [isoCode], e.g. "+234" for Nigeria.
String callingCodeFor(IsoCode isoCode) =>
    '+${PhoneNumber(isoCode: isoCode, nsn: '').countryCode}';

const List<(String, IsoCode)> _entries = [
  ('Ascension Island', IsoCode.AC),
  ('Andorra', IsoCode.AD),
  ('United Arab Emirates', IsoCode.AE),
  ('UAE', IsoCode.AE),
  ('Afghanistan', IsoCode.AF),
  ('Antigua and Barbuda', IsoCode.AG),
  ('Anguilla', IsoCode.AI),
  ('Albania', IsoCode.AL),
  ('Armenia', IsoCode.AM),
  ('Angola', IsoCode.AO),
  ('Argentina', IsoCode.AR),
  ('American Samoa', IsoCode.AS),
  ('Austria', IsoCode.AT),
  ('Australia', IsoCode.AU),
  ('Aruba', IsoCode.AW),
  ('Åland Islands', IsoCode.AX),
  ('Aland Islands', IsoCode.AX),
  ('Azerbaijan', IsoCode.AZ),
  ('Bosnia and Herzegovina', IsoCode.BA),
  ('Barbados', IsoCode.BB),
  ('Bangladesh', IsoCode.BD),
  ('Belgium', IsoCode.BE),
  ('Burkina Faso', IsoCode.BF),
  ('Bulgaria', IsoCode.BG),
  ('Bahrain', IsoCode.BH),
  ('Burundi', IsoCode.BI),
  ('Benin', IsoCode.BJ),
  ('Saint Barthélemy', IsoCode.BL),
  ('Saint Barthelemy', IsoCode.BL),
  ('Bermuda', IsoCode.BM),
  ('Brunei', IsoCode.BN),
  ('Brunei Darussalam', IsoCode.BN),
  ('Bolivia', IsoCode.BO),
  ('Bonaire, Sint Eustatius and Saba', IsoCode.BQ),
  ('Caribbean Netherlands', IsoCode.BQ),
  ('Brazil', IsoCode.BR),
  ('Bahamas', IsoCode.BS),
  ('The Bahamas', IsoCode.BS),
  ('Bhutan', IsoCode.BT),
  ('Botswana', IsoCode.BW),
  ('Belarus', IsoCode.BY),
  ('Belize', IsoCode.BZ),
  ('Canada', IsoCode.CA),
  ('Cocos (Keeling) Islands', IsoCode.CC),
  ('Cocos Islands', IsoCode.CC),
  ('Democratic Republic of the Congo', IsoCode.CD),
  ('DR Congo', IsoCode.CD),
  ('Congo, Democratic Republic of the', IsoCode.CD),
  ('Congo-Kinshasa', IsoCode.CD),
  ('Central African Republic', IsoCode.CF),
  ('Republic of the Congo', IsoCode.CG),
  ('Congo', IsoCode.CG),
  ('Congo-Brazzaville', IsoCode.CG),
  ('Switzerland', IsoCode.CH),
  ("Côte d'Ivoire", IsoCode.CI),
  ('Cote d\'Ivoire', IsoCode.CI),
  ('Ivory Coast', IsoCode.CI),
  ('Cook Islands', IsoCode.CK),
  ('Chile', IsoCode.CL),
  ('Cameroon', IsoCode.CM),
  ('China', IsoCode.CN),
  ('Colombia', IsoCode.CO),
  ('Costa Rica', IsoCode.CR),
  ('Cuba', IsoCode.CU),
  ('Cape Verde', IsoCode.CV),
  ('Cabo Verde', IsoCode.CV),
  ('Curaçao', IsoCode.CW),
  ('Curacao', IsoCode.CW),
  ('Christmas Island', IsoCode.CX),
  ('Cyprus', IsoCode.CY),
  ('Czech Republic', IsoCode.CZ),
  ('Czechia', IsoCode.CZ),
  ('Germany', IsoCode.DE),
  ('Djibouti', IsoCode.DJ),
  ('Denmark', IsoCode.DK),
  ('Dominica', IsoCode.DM),
  ('Dominican Republic', IsoCode.DO),
  ('Algeria', IsoCode.DZ),
  ('Ecuador', IsoCode.EC),
  ('Estonia', IsoCode.EE),
  ('Egypt', IsoCode.EG),
  ('Western Sahara', IsoCode.EH),
  ('Eritrea', IsoCode.ER),
  ('Spain', IsoCode.ES),
  ('Ethiopia', IsoCode.ET),
  ('Finland', IsoCode.FI),
  ('Fiji', IsoCode.FJ),
  ('Falkland Islands', IsoCode.FK),
  ('Micronesia', IsoCode.FM),
  ('Federated States of Micronesia', IsoCode.FM),
  ('Faroe Islands', IsoCode.FO),
  ('France', IsoCode.FR),
  ('Gabon', IsoCode.GA),
  ('United Kingdom', IsoCode.GB),
  ('UK', IsoCode.GB),
  ('Great Britain', IsoCode.GB),
  ('Grenada', IsoCode.GD),
  ('Georgia', IsoCode.GE),
  ('French Guiana', IsoCode.GF),
  ('Guernsey', IsoCode.GG),
  ('Ghana', IsoCode.GH),
  ('Gibraltar', IsoCode.GI),
  ('Greenland', IsoCode.GL),
  ('Gambia', IsoCode.GM),
  ('The Gambia', IsoCode.GM),
  ('Guinea', IsoCode.GN),
  ('Guadeloupe', IsoCode.GP),
  ('Equatorial Guinea', IsoCode.GQ),
  ('Greece', IsoCode.GR),
  ('Guatemala', IsoCode.GT),
  ('Guam', IsoCode.GU),
  ('Guinea-Bissau', IsoCode.GW),
  ('Guyana', IsoCode.GY),
  ('Hong Kong', IsoCode.HK),
  ('Honduras', IsoCode.HN),
  ('Croatia', IsoCode.HR),
  ('Haiti', IsoCode.HT),
  ('Hungary', IsoCode.HU),
  ('Indonesia', IsoCode.ID),
  ('Ireland', IsoCode.IE),
  ('Israel', IsoCode.IL),
  ('Isle of Man', IsoCode.IM),
  ('India', IsoCode.IN),
  ('British Indian Ocean Territory', IsoCode.IO),
  ('Iraq', IsoCode.IQ),
  ('Iran', IsoCode.IR),
  ('Iceland', IsoCode.IS),
  ('Italy', IsoCode.IT),
  ('Jersey', IsoCode.JE),
  ('Jamaica', IsoCode.JM),
  ('Jordan', IsoCode.JO),
  ('Japan', IsoCode.JP),
  ('Kenya', IsoCode.KE),
  ('Kyrgyzstan', IsoCode.KG),
  ('Cambodia', IsoCode.KH),
  ('Kiribati', IsoCode.KI),
  ('Comoros', IsoCode.KM),
  ('Saint Kitts and Nevis', IsoCode.KN),
  ('North Korea', IsoCode.KP),
  ("Korea, Democratic People's Republic of", IsoCode.KP),
  ('South Korea', IsoCode.KR),
  ('Korea, Republic of', IsoCode.KR),
  ('Korea', IsoCode.KR),
  ('Kuwait', IsoCode.KW),
  ('Cayman Islands', IsoCode.KY),
  ('Kazakhstan', IsoCode.KZ),
  ('Laos', IsoCode.LA),
  ("Lao People's Democratic Republic", IsoCode.LA),
  ('Lebanon', IsoCode.LB),
  ('Saint Lucia', IsoCode.LC),
  ('Liechtenstein', IsoCode.LI),
  ('Sri Lanka', IsoCode.LK),
  ('Liberia', IsoCode.LR),
  ('Lesotho', IsoCode.LS),
  ('Lithuania', IsoCode.LT),
  ('Luxembourg', IsoCode.LU),
  ('Latvia', IsoCode.LV),
  ('Libya', IsoCode.LY),
  ('Morocco', IsoCode.MA),
  ('Monaco', IsoCode.MC),
  ('Moldova', IsoCode.MD),
  ('Montenegro', IsoCode.ME),
  ('Saint Martin', IsoCode.MF),
  ('Madagascar', IsoCode.MG),
  ('Marshall Islands', IsoCode.MH),
  ('North Macedonia', IsoCode.MK),
  ('Macedonia', IsoCode.MK),
  ('Mali', IsoCode.ML),
  ('Myanmar', IsoCode.MM),
  ('Burma', IsoCode.MM),
  ('Mongolia', IsoCode.MN),
  ('Macau', IsoCode.MO),
  ('Macao', IsoCode.MO),
  ('Northern Mariana Islands', IsoCode.MP),
  ('Martinique', IsoCode.MQ),
  ('Mauritania', IsoCode.MR),
  ('Montserrat', IsoCode.MS),
  ('Malta', IsoCode.MT),
  ('Mauritius', IsoCode.MU),
  ('Maldives', IsoCode.MV),
  ('Malawi', IsoCode.MW),
  ('Mexico', IsoCode.MX),
  ('Malaysia', IsoCode.MY),
  ('Mozambique', IsoCode.MZ),
  ('Namibia', IsoCode.NA),
  ('New Caledonia', IsoCode.NC),
  ('Niger', IsoCode.NE),
  ('Norfolk Island', IsoCode.NF),
  ('Nigeria', IsoCode.NG),
  ('Nicaragua', IsoCode.NI),
  ('Netherlands', IsoCode.NL),
  ('The Netherlands', IsoCode.NL),
  ('Norway', IsoCode.NO),
  ('Nepal', IsoCode.NP),
  ('Nauru', IsoCode.NR),
  ('Niue', IsoCode.NU),
  ('New Zealand', IsoCode.NZ),
  ('Oman', IsoCode.OM),
  ('Panama', IsoCode.PA),
  ('Peru', IsoCode.PE),
  ('French Polynesia', IsoCode.PF),
  ('Papua New Guinea', IsoCode.PG),
  ('Philippines', IsoCode.PH),
  ('Pakistan', IsoCode.PK),
  ('Poland', IsoCode.PL),
  ('Saint Pierre and Miquelon', IsoCode.PM),
  ('Puerto Rico', IsoCode.PR),
  ('Palestine', IsoCode.PS),
  ('Palestine, State of', IsoCode.PS),
  ('Portugal', IsoCode.PT),
  ('Palau', IsoCode.PW),
  ('Paraguay', IsoCode.PY),
  ('Qatar', IsoCode.QA),
  ('Réunion', IsoCode.RE),
  ('Reunion', IsoCode.RE),
  ('Romania', IsoCode.RO),
  ('Serbia', IsoCode.RS),
  ('Russia', IsoCode.RU),
  ('Russian Federation', IsoCode.RU),
  ('Rwanda', IsoCode.RW),
  ('Saudi Arabia', IsoCode.SA),
  ('Solomon Islands', IsoCode.SB),
  ('Seychelles', IsoCode.SC),
  ('Sudan', IsoCode.SD),
  ('Sweden', IsoCode.SE),
  ('Singapore', IsoCode.SG),
  ('Saint Helena', IsoCode.SH),
  ('Slovenia', IsoCode.SI),
  ('Svalbard and Jan Mayen', IsoCode.SJ),
  ('Slovakia', IsoCode.SK),
  ('Sierra Leone', IsoCode.SL),
  ('San Marino', IsoCode.SM),
  ('Senegal', IsoCode.SN),
  ('Somalia', IsoCode.SO),
  ('Suriname', IsoCode.SR),
  ('South Sudan', IsoCode.SS),
  ('Sao Tome and Principe', IsoCode.ST),
  ('São Tomé and Príncipe', IsoCode.ST),
  ('El Salvador', IsoCode.SV),
  ('Sint Maarten', IsoCode.SX),
  ('Syria', IsoCode.SY),
  ('Syrian Arab Republic', IsoCode.SY),
  ('Eswatini', IsoCode.SZ),
  ('Swaziland', IsoCode.SZ),
  ('Tristan da Cunha', IsoCode.TA),
  ('Turks and Caicos Islands', IsoCode.TC),
  ('Chad', IsoCode.TD),
  ('Togo', IsoCode.TG),
  ('Thailand', IsoCode.TH),
  ('Tajikistan', IsoCode.TJ),
  ('Tokelau', IsoCode.TK),
  ('Timor-Leste', IsoCode.TL),
  ('East Timor', IsoCode.TL),
  ('Turkmenistan', IsoCode.TM),
  ('Tunisia', IsoCode.TN),
  ('Tonga', IsoCode.TO),
  ('Turkey', IsoCode.TR),
  ('Türkiye', IsoCode.TR),
  ('Trinidad and Tobago', IsoCode.TT),
  ('Tuvalu', IsoCode.TV),
  ('Taiwan', IsoCode.TW),
  ('Tanzania', IsoCode.TZ),
  ('United Republic of Tanzania', IsoCode.TZ),
  ('Ukraine', IsoCode.UA),
  ('Uganda', IsoCode.UG),
  ('United States', IsoCode.US),
  ('United States of America', IsoCode.US),
  ('USA', IsoCode.US),
  ('US', IsoCode.US),
  ('Uruguay', IsoCode.UY),
  ('Uzbekistan', IsoCode.UZ),
  ('Vatican City', IsoCode.VA),
  ('Holy See', IsoCode.VA),
  ('Saint Vincent and the Grenadines', IsoCode.VC),
  ('Venezuela', IsoCode.VE),
  ('British Virgin Islands', IsoCode.VG),
  ('U.S. Virgin Islands', IsoCode.VI),
  ('US Virgin Islands', IsoCode.VI),
  ('Vietnam', IsoCode.VN),
  ('Viet Nam', IsoCode.VN),
  ('Vanuatu', IsoCode.VU),
  ('Wallis and Futuna', IsoCode.WF),
  ('Samoa', IsoCode.WS),
  ('Kosovo', IsoCode.XK),
  ('Yemen', IsoCode.YE),
  ('Mayotte', IsoCode.YT),
  ('South Africa', IsoCode.ZA),
  ('Zambia', IsoCode.ZM),
  ('Zimbabwe', IsoCode.ZW),
];
