subprojects { subproject ->
    if (subproject.name == 'pusher_channels_flutter') {
        subproject.afterEvaluate {
            // Remove the package attribute from the AndroidManifest.xml
            def manifestFile = file("${subproject.projectDir}/src/main/AndroidManifest.xml")
            if (manifestFile.exists()) {
                def manifestContent = manifestFile.text
                manifestContent = manifestContent.replaceAll('package="com.pusher.channels_flutter"', '')
                manifestFile.text = manifestContent
            }

            // Add the namespace property to build.gradle
            subproject.android {
                namespace = 'com.pusher.channels_flutter'
            }
        }
    }
}

subprojects { subproject ->
    if (subproject.name == 'tiktok_login_flutter') {
        subproject.afterEvaluate {
            // Remove the package attribute from the AndroidManifest.xml
            def manifestFile = file("${subproject.projectDir}/src/main/AndroidManifest.xml")
            if (manifestFile.exists()) {
                def manifestContent = manifestFile.text
                manifestContent = manifestContent.replaceAll('package="com.raiinmaker.tiktok_login_flutter"', '')
                manifestFile.text = manifestContent
            }

            // Add the namespace property to build.gradle
            subproject.android {
                namespace = 'com.raiinmaker.tiktok_login_flutter'
            }
        }
    }
}

subprojects { subproject ->
    if (subproject.name == 'video_thumbnail') {
        subproject.afterEvaluate {
            def manifestFile = file("${subproject.projectDir}/src/main/AndroidManifest.xml")
            if (manifestFile.exists()) {
                def manifestContent = manifestFile.text
                manifestContent = manifestContent.replaceAll('package="xyz.justsoft.video_thumbnail"', '')
                manifestFile.text = manifestContent
            }
            subproject.android {
                namespace = 'xyz.justsoft.video_thumbnail'
            }
        }
    }
}

subprojects { subproject ->
    if (subproject.name == 'device_info') {
        subproject.afterEvaluate {
            def manifestFile = file("${subproject.projectDir}/src/main/AndroidManifest.xml")
            if (manifestFile.exists()) {
                def manifestContent = manifestFile.text
                manifestContent = manifestContent.replaceAll('package="io.flutter.plugins.deviceinfo"', '')
                manifestFile.text = manifestContent
            }
            subproject.android {
                namespace = 'io.flutter.plugins.deviceinfo'
            }
        }
    }
}