// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5eMZEDlzdYgJyPzCppQwulRg5ZA-JMk',
    appId: '1:631667238707:android:4526e6c7893a9091acc046',
    messagingSenderId: '631667238707',
    projectId: 'talkam-1',
    storageBucket: 'talkam-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmaTQrqGDxVPz-jXcR3uk7td94BZAfmBM',
    appId: '1:631667238707:ios:9e4f79c6842957b0acc046',
    messagingSenderId: '631667238707',
    projectId: 'talkam-1',
    storageBucket: 'talkam-1.firebasestorage.app',
    androidClientId: '631667238707-sn2i3p9nm4rum1ktq84to000tgm8887v.apps.googleusercontent.com',
    iosClientId: '631667238707-2rdclmurshivbhgluafsshnq5rj8e73c.apps.googleusercontent.com',
    iosBundleId: 'com.talkamtechservice.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZk-Lns5LOM0q0RgWZqY9LXeu_ZBq1Zyk',
    appId: '1:478885302787:web:a1b3ec1a48046c1a807436',
    messagingSenderId: '478885302787',
    projectId: 'talkam-temp',
    authDomain: 'talkam-temp.firebaseapp.com',
    storageBucket: 'talkam-temp.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNIPDDGTmviX0itRrEStBEpBJnvX2Ul6Y',
    appId: '1:478885302787:ios:618205e62da88787807436',
    messagingSenderId: '478885302787',
    projectId: 'talkam-temp',
    storageBucket: 'talkam-temp.appspot.com',
    androidClientId: '478885302787-32qfubm0damgpkn5tm0tt655s09e3sfq.apps.googleusercontent.com',
    iosClientId: '478885302787-vq9cik065d8806umib3uc3htghoslvim.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQ7aHAj_1lpjBgMbudOu-l82lVklPZBU',
    appId: '1:478885302787:web:1504ba25ba5e94cc807436',
    messagingSenderId: '478885302787',
    projectId: 'talkam-temp',
    authDomain: 'talkam-temp.firebaseapp.com',
    storageBucket: 'talkam-temp.appspot.com',
  );

}